# Generated by Django 4.2.29 on 2026-06-25 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_filename',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='download_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesses', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchased_products',
            },
        ),
        migrations.AddConstraint(
            model_name='purchasedproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_active_product_access_per_user'),
        ),
    ]
