# Generated by Django 6.0.6 on 2026-07-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_compare_at_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
