# Generated by Django 6.0.6 on 2026-07-02 02:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_preference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NvidiaSettings',
            fields=[
                ('id', models.CharField(default='nvidia', max_length=50, primary_key=True, serialize=False)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('base_url', models.URLField(default='https://integrate.api.nvidia.com/v1', max_length=500)),
                ('model', models.CharField(blank=True, max_length=300)),
                ('image_model', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NVIDIA settings',
                'verbose_name_plural': 'NVIDIA settings',
                'db_table': 'nvidia_settings',
            },
        ),
        migrations.CreateModel(
            name='WorkbookDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('brief', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('age', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=100)),
                ('pages', models.PositiveIntegerField(default=20)),
                ('style', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(default='local', max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('building', 'Building'), ('done', 'Done'), ('error', 'Error')], default='planned', max_length=20)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workbook_drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
