# Generated by Django 6.0.6 on 2026-07-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_nvidiasettings_workbookdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvidiasettings',
            name='workbook_build_model',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='nvidiasettings',
            name='workbook_plan_model',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='nvidiasettings',
            name='workbook_skill',
            field=models.TextField(blank=True),
        ),
    ]
