# Generated by Django 6.0.6 on 2026-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_nvidiasettings_model_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
