# Generated by Django 4.2.29 on 2026-07-10 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_purchase_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('channel', models.CharField(default='email', max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=300)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mercadopago', max_length=50)),
                ('provider_payment_id', models.CharField(max_length=200, unique=True)),
                ('preference_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('status_detail', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ARS', max_length=10)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mercadopago', max_length=50)),
                ('provider_event_id', models.CharField(blank=True, max_length=200)),
                ('provider_payment_id', models.CharField(blank=True, max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_events',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('account_registered', 'Account Registered'), ('email_verified', 'Email Verified'), ('login', 'Login'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('avatar_updated', 'Avatar Updated'), ('avatar_deleted', 'Avatar Deleted'), ('checkout_started', 'Checkout Started'), ('payment_pending', 'Payment Pending'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('payment_refunded', 'Payment Refunded'), ('library_access_granted', 'Library Access Granted'), ('material_downloaded', 'Material Downloaded'), ('email_queued', 'Email Queued'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('profile_updated', 'Profile Updated')], max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('avatar_public_id', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.RemoveConstraint(
            model_name='purchasedproduct',
            name='unique_active_product_access_per_user',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_token_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='purchasedproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'product'), name='unique_active_product_access_per_user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['provider_payment_id', 'event_type'], name='payment_eve_provide_4b35d4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payload_hash'], name='payment_eve_payload_712955_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(condition=~models.Q(provider_event_id=''), fields=('provider', 'provider_event_id'), name='unique_provider_payment_event'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', 'event_type'], name='user_events_user_id_537eba_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', 'created_at'], name='user_events_event_t_101e03_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_payment_id'], name='payments_provide_340c17_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_order_i_3d4604_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type'], name='notificatio_user_id_6b5847_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['order', 'type'], name='notificatio_order_i_fa7e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notificatio_status_fce6f5_idx'),
        ),
    ]
